### ISSUE TITLE
Add support for Apps

### ISSUE THREAD

**Issue by robertlugg** [onnovalkering/vscode-singularity#3]
It's now possible to create "Apps"
https://sylabs.io/guides/3.2/user-guide/definition_files.html#apps

The request is to modify to highlight `%apprun` as well as the other sections which support Apps.

These 'apps' sections take an argument which is the app name.  It would also be nice to somehow syntax check that a name was added.

**Comment by onnovalkering** [comment]
I've published a new release just now (0.5.0) that adds highlighting for the `%app*` sections.
I'll look into the syntax checking when I have more time available.

**Comment by robertlugg** [comment]
Looks good.  Thank you.
