### ISSUE TITLE
How to pull container image from Docker Hub?

### ISSUE THREAD

**Issue by Nobuyuki-Enzan** [onnovalkering/vscode-singularity#4]
I'm interested in developing inside a container using VS code.
Unfortunately we cannot build a container image in the supercomputer.

First, I created a Docker image, and pushed it to Docker Hub.
Second, I login to the supercomputer through SSH, pull a container image from Docker Hub (and converted to .sif file).
But, I don't know how to execute the container image (.sif file) using this vscode-singularity.

Could you please tell me how to do this?

**Comment by onnovalkering** [comment]
Unfortunately, this extension only provides syntax highlighting for Singularity definition files. 

I believe this page is relevant for your use-case: https://github.com/microsoft/vscode-remote-release/issues/3066.

**Comment by Nobuyuki-Enzan** [comment]
I'm sorry for taking your time.
And thank you for the suggestion.
