### ISSUE TITLE
Upload to Open VSX Registry

### ISSUE THREAD

**Issue by nlvw** [onnovalkering/vscode-singularity#5]
Thanks for this project!  

Would you consider also uploading to the [Open VSX Registry](https://open-vsx.org/)?  This would make your plugin available to open source versions of VSCode and other code in browser projects like https://github.com/coder/code-server

**Comment by onnovalkering** [comment]
Hello, thank you for the suggestion! I've published the extension on the Open VSX registry:

https://open-vsx.org/extension/onnovalkering/vscode-singularity

The namespace isn't mine yet ([#1316](https://github.com/EclipseFdn/open-vsx.org/issues/1316)), but it should already be usable. 
Let me know if you encounter any problems with the extension in VSCodium, Coder, or any other VS Code derivative.

**Comment by nlvw** [comment]
Just tested it in code-server and it worked without issue.  Thanks!

**Comment by onnovalkering** [comment]
Great! Thanks.
